import React, { createContext, useContext, useState, useEffect } from 'react';
import { Toaster } from "sonner";

const translations = {
  en: {
    // Navigation
    home: "Home",
    myDocuments: "My Documents",
    newDocument: "New Document",
    suggestions: "Suggestions",
    yourStats: "Your Stats",
    logout: "Logout",
    signIn: "Sign In",
    profile: "Profile",
    
    // Document
    addSection: "Add Section",
    editSection: "Edit Section",
    pendingEditSuggestion: "Pending Edit Suggestion",
    viewDetails: "View Details",
    proposedChanges: "Proposed Changes",
    lastEdited: "Last edited",
    comments: "Comments",
    admin: "Admin",
    versions: "Versions",
    
    // Suggestions
    newSuggestion: "New Suggestion",
    createNewTopic: "Create new topic",
    enterNewTopicName: "Enter new topic name...",
    topic: "Topic",
    content: "Content",
    explanation: "Explanation (optional)",
    createSuggestion: "Create Suggestion",
    cancel: "Cancel",
    
    // Voting
    votePro: "Vote Pro",
    voteCon: "Vote Con",
    proVotes: "Pro Votes",
    conVotes: "Con Votes",
    consensus: "Consensus",
    votesNeeded: "votes needed",
    passedConsensus: "Passed consensus!",
    cannotPass: "Cannot pass",
    
    // Status
    pending: "Pending",
    accepted: "Accepted",
    rejected: "Rejected",
    
    // Stats
    contributors: "Contributors",
    avgConsensus: "Avg Consensus",
    threshold: "Threshold",
    activeDocuments: "Active Documents",
    collaborators: "Participants",
    
    // Home
    democraticCollaboration: "Democratic Collaboration Platform",
    buildConsensus: "Build Consensus, Draft Together",
    platformDescription: "Collaborative platform for drafting policy documents, constitutions, and decisions through transparent voting and dynamic consensus algorithms.",
    getStarted: "Get Started",
    learnMore: "Learn More",
    recentDocuments: "Recent Documents",
    browseContribute: "Browse and contribute to ongoing collaborative drafts",
    
    // Misc
    by: "By",
    noSectionsYet: "No sections yet.",
    noTopicsYet: "No topics defined yet.",
    loading: "Loading...",
    insertSectionHere: "Insert section here",
    votingEnded: "Voting ended",
    remaining: "remaining",
    language: "Language",
    
    // Additional translations
    suggestNewSection: "Suggest New Section",
    suggestEditSection: "Suggest Edit to Section",
    enterContent: "Enter the content...",
    explainChange: "Explain why this change is needed...",
    creating: "Creating...",
    sectionContent: "Section Content",
    noSuggestionsYet: "No Suggestions Yet",
    beFirstToSuggest: "Be the first to suggest a change to this document",
    newSection: "New Section",
    left: "left",
    created: "Created",
    commentsCount: "Comments",
    replyingTo: "Replying to",
    writeReply: "Write a reply...",
    addComment: "Add comment...",
    postComment: "Post Comment",
    loadingComments: "Loading comments...",
    noCommentsYet: "No comments yet.",
    beFirstToComment: "Be the first to comment!",
    reply: "Reply",
    delete: "Delete",
    passedConsensusThreshold: "Passed consensus threshold!",
    fullAgreementNeeded: "Full agreement needed",
    votesNeededToPass: "{count} votes needed to pass",
    noDocumentsYet: "No Documents Yet",
    beFirstToCreate: "Be the first to create a collaborative document",
    documentNotFound: "Document not found",
    goHome: "Go Home",
    document: "Document",
    versionHistory: "Version History",
    compareVersions: "Compare Versions",
    cancelComparison: "Cancel Comparison",
    noPreviousVersions: "No Previous Versions",
    documentChangesSavedAutomatically: "Document changes are saved automatically as versions.",
    changeWithoutDescription: "Change without description",
    confirmRestoreVersion: "Are you sure you want to restore this version? The current version will be saved in history.",
    restoreVersion: "Restore Version",
    adminAccessRequired: "Admin access required",
    version: "Version",
    restoredFromVersion: "Restored from version {version}",
    viewInDocument: "View in Document",
    activitySummary: "Activity Summary",
    contributionDescription: "Your contribution and points history",
    pointsHistory: "Points History",
    noPointsHistory: "No points history yet",
    gamificationPoints: "Gamification Points",
    suggestionsCreated: "Suggestions Created",
    accountType: "Account Type",
    translateAll: "Translate All",
    translating: "Translating...",
    translateSection: "Translate Section",
    translatedFrom: "Translated from",
    points: "Points",
    navigation: "Navigation",
    costToCreate: "Cost to create suggestion:",
    yourPoints: "Your points:",
    originalContent: "Original Content:",
    cleanView: "Clean View",
    viewCurrentVersion: "View Current Version",
    section: "Section",
    history: "History",
    personalInformation: "Personal Information",
    displayName: "Display Name",
    email: "Email",
    role: "Role",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    action: "Action",
    amount: "Amount",
    description: "Description",
    date: "Date",
    saving: "Saving...",
    suggestionNotFound: "Suggestion not found",
    proArguments: "Pro Arguments",
    conArguments: "Con Arguments",
    noProArgumentsYet: "No pro arguments yet",
    noConArgumentsYet: "No con arguments yet",
    addProArgument: "Add Pro Argument",
    addConArgument: "Add Con Argument",
    writeProArgument: "Write your pro argument...",
    writeConArgument: "Write your con argument...",
    submit: "Submit",
    proposedContent: "Proposed Content",
    currentVersion: "Current Version",
    confirmDeleteSuggestion: "Are you sure you want to delete this suggestion?",
    deleteSuggestion: "Delete Suggestion",
    commentsOnSuggestion: "Comments on Suggestion",
    onlyCreatorCanDelete: "Only the creator can delete this suggestion",
    mustBeLoggedInToVote: "Must be logged in to vote",
    argumentContentRequired: "Argument content is required",
    mustBeLoggedIn: "Must be logged in",
    acceptSuggestion: "Accept Suggestion",
    rejectSuggestion: "Reject Suggestion",
    sectionHistory: "Section History",
    createNewDocument: "Create New Document",
    fillDetailsBelow: "Fill in the details below to create a new collaborative document",
    signInToViewPrivate: "Sign in to view private documents",
    signInToParticipate: "Sign in to participate and create suggestions",
    previousSuggestion: "Previous",
    nextSuggestion: "Next",
    suggestionToEditSection: "Suggestion to Edit Section",
    newSectionIn: "New section in {topic}",
    editSectionIn: "Edit section in {topic}",
    changeDescription: "Change Description",
    sectionNotFound: "Section not found",
    current: "Current",
    lastUpdate: "Last update",
    previousVersions: "Previous Versions",
    noDescription: "No description",
    suggestionAccepted: "Suggestion Accepted",
    sectionCreated: "Section Created",
    directEdit: "Direct Edit",
    viewFullDiscussion: "View Full Discussion",
    changesInThisVersion: "Changes in this version",
    explanationForSuggestion: "Explanation for suggestion",
    pro: "Pro",
    con: "Con",
    publishedBy: "Published by",
    acceptedOn: "Accepted on",
    sectionChangesAutomaticallySaved: "Changes to this section will be saved here automatically",
    deleteSection: "Delete Section",
    confirmDeleteSection: "Are you sure you want to delete this section?",
    saveToHistory: "Save to version history before deleting",
    sectionDeleted: "Section deleted successfully",
    deleting: "Deleting...",
    editSuggestions: "Edit Suggestions",
    noContributors: "No contributors yet",
    translate: "Translate",
    showOriginal: "Show Original",
    showTranslation: "Show Translation",
    showDiff: "Show Changes",
    activityOf: "Activity of {name}",
    suggestionsPublishedByMe: "Edit suggestions I published",
    suggestionsPublishedBy: "Edit suggestions published by {name}",
    commentsPublishedByMe: "Comments I published",
    commentsPublishedBy: "Comments published by {name}",
    activityHistoryOf: "Activity history of {name}",
    noActivityHistory: "No activity history yet",
    commentOn: "Comment on",
    viewFullComment: "View full comment",
    suggestion: "suggestion",
    section: "section",
    },
  he: {
    // ניווט
    home: "בית",
    myDocuments: "המסמכים שלי",
    newDocument: "מסמך חדש",
    suggestions: "הצעות",
    yourStats: "הסטטיסטיקות שלך",
    logout: "התנתק",
    signIn: "התחבר",
    profile: "פרופיל",
    
    // מסמך
    addSection: "הוסף סעיף",
    editSection: "ערוך סעיף",
    pendingEditSuggestion: "הצעת עריכה ממתינה",
    viewDetails: "צפה בפרטים",
    proposedChanges: "שינויים מוצעים",
    lastEdited: "נערך לאחרונה",
    comments: "תגובות",
    admin: "ניהול",
    versions: "גרסאות",
    
    // הצעות
    newSuggestion: "הצעה חדשה",
    createNewTopic: "צור נושא חדש",
    enterNewTopicName: "הזן שם נושא חדש...",
    topic: "נושא",
    content: "תוכן",
    explanation: "הסבר (אופציונלי)",
    createSuggestion: "צור הצעה",
    cancel: "ביטול",
    
    // הצבעה
    votePro: "הצבע בעד",
    voteCon: "הצבע נגד",
    proVotes: "הצבעות בעד",
    conVotes: "הצבעות נגד",
    consensus: "קונצנזוס",
    votesNeeded: "הצבעות נדרשות",
    passedConsensus: "עבר את סף הקונסנזוס!",
    cannotPass: "לא יכול לעבור",
    
    // סטטוס
    pending: "ממתין",
    accepted: "התקבל",
    rejected: "נדחה",
    
    // סטטיסטיקות
    contributors: "משתתפים",
    avgConsensus: "קונצנזוס ממוצע",
    threshold: "סף",
    activeDocuments: "מסמכים פעילים",
    collaborators: "משתתפים",
    
    // דף הבית
    democraticCollaboration: "פלטפורמת שיתוף פעולה דמוקרטי",
    buildConsensus: "בנו קונצננזוס, נסחו ביחד",
    platformDescription: "פלטפורמה לשיתוף פעולה לניסוח מסמכי מדיניות, חוקות והחלטות באמצעות הצבעה שקופה ואלגוריתמי קונצנזוס דינמיים.",
    getStarted: "התחל",
    learnMore: "למד עוד",
    recentDocuments: "מסמכים אחרונים",
    browseContribute: "עיין ותרום למסמכים משותפים מתמשכים",
    
    // שונות
    by: "על ידי",
    noSectionsYet: "אין סעיפים עדיין.",
    noTopicsYet: "אין נושאים עדיין.",
    loading: "טוען...",
    insertSectionHere: "הוסף סעיף כאן",
    votingEnded: "ההצבעה הסתיימה",
    remaining: "נותרו",
    language: "שפה",
    
    // תרגומים נוספים
    suggestNewSection: "הצע סעיף חדש",
    suggestEditSection: "הצע עריכה לסעיף",
    enterContent: "הזן את התוכן...",
    explainChange: "הסבר מדוע השינוי נדרש...",
    creating: "יוצר...",
    sectionContent: "תוכן הסעיף",
    noSuggestionsYet: "אין הצעות עדיין",
    beFirstToSuggest: "היה הראשון להציע שינוי למסמך זה",
    newSection: "סעיף חדש",
    left: "נותרו",
    created: "נוצר",
    commentsCount: "תגובות",
    replyingTo: "משיב ל",
    writeReply: "כתוב תגובה...",
    addComment: "הוסף תגובה...",
    postComment: "פרסם תגובה",
    loadingComments: "טוען תגובות...",
    noCommentsYet: "אין תגובות עדיין.",
    beFirstToComment: "היה הראשון להגיב!",
    reply: "השב",
    delete: "מחק",
    passedConsensusThreshold: "עבר את סף הקונסנזוס!",
    fullAgreementNeeded: "דרושה הסכמה מלאה",
    votesNeededToPass: "חסרים {count} תומכים לאישור",
    noDocumentsYet: "אין מסמכים עדיין",
    beFirstToCreate: "היה הראשון ליצור מסמך שיתופי",
    documentNotFound: "המסמך לא נמצא",
    goHome: "חזור לדף הבית",
    document: "מסמך",
    versionHistory: "היסטוריית גרסאות",
    compareVersions: "השווה גרסאות",
    cancelComparison: "בטל השוואה",
    noPreviousVersions: "אין גרסאות קודמות",
    documentChangesSavedAutomatically: "שינויים במסמך נשמרים אוטומטית כגרסאות.",
    changeWithoutDescription: "שינוי ללא תיאור",
    confirmRestoreVersion: "האם לשחזר גרסה זו? הגרסה הנוכחית תישמר בהיסטוריה.",
    restoreVersion: "שחזר גרסה",
    adminAccessRequired: "נדרשת הרשאת מנהל",
    version: "גרסה",
    restoredFromVersion: "שוחזר מגרסה {version}",
    viewInDocument: "צפה במסמך",
    activitySummary: "סיכום פעילות",
    contributionDescription: "התרומה שלך והיסטוריית הנקודות",
    pointsHistory: "היסטוריית נקודות",
    noPointsHistory: "אין עדיין היסטוריית נקודות",
    gamificationPoints: "נקודות גיימיפיקציה",
    suggestionsCreated: "הצעות שנוצרו",
    accountType: "סוג חשבון",
    translateAll: "תרגם הכל",
    translating: "מתרגם...",
    translateSection: "תרגם סעיף",
    translatedFrom: "תורגם מ",
    points: "נקודות",
    navigation: "ניווט",
    costToCreate: "עלות יצירת הצעה:",
    yourPoints: "הנקודות שלך:",
    originalContent: "התוכן המקורי:",
    cleanView: "תצוגה נקייה",
    viewCurrentVersion: "לצפייה בגרסת המסמך העדכנית",
    section: "סעיף",
    history: "היסטוריה",
    personalInformation: "מידע אישי",
    displayName: "שם תצוגה",
    email: "אימייל",
    role: "תפקיד",
    editProfile: "ערוך פרופיל",
    saveChanges: "שמור שינויים",
    action: "פעולה",
    amount: "כמות",
    description: "תיאור",
    date: "תאריך",
    saving: "שומר...",
    suggestionNotFound: "ההצעה לא נמצאה",
    proArguments: "טיעונים בעד",
    conArguments: "טיעונים נגד",
    noProArgumentsYet: "אין עדיין טיעונים בעד",
    noConArgumentsYet: "אין עדיין טיעונים נגד",
    addProArgument: "הוסף טיעון בעד",
    addConArgument: "הוסף טיעון נגד",
    writeProArgument: "כתוב את הטיעון בעד...",
    writeConArgument: "כתוב את הטיעון נגד...",
    submit: "שלח",
    proposedContent: "תוכן מוצע",
    currentVersion: "גרסה נוכחית",
    confirmDeleteSuggestion: "האם אתה בטוח שברצונך למחוק הצעה זו?",
    deleteSuggestion: "מחק הצעה",
    commentsOnSuggestion: "תגובות על ההצעה",
    onlyCreatorCanDelete: "רק היוצר יכול למחוק הצעה זו",
    mustBeLoggedInToVote: "יש להתחבר כדי להצביע",
    argumentContentRequired: "נדרש תוכן טיעון",
    mustBeLoggedIn: "יש להתחבר",
    acceptSuggestion: "אשר הצעה",
    rejectSuggestion: "דחה הצעה",
    sectionHistory: "היסטוריית סעיף",
    createNewDocument: "יצירת מסמך חדש",
    fillDetailsBelow: "מלא את הפרטים למטה כדי ליצור מסמך שיתופי חדש",
    signInToViewPrivate: "התחבר כדי לצפות במסמכים פרטיים",
    signInToParticipate: "התחבר כדי להשתתף וליצור הצעות",
    previousSuggestion: "הצעה קודמת",
    nextSuggestion: "הצעה הבאה",
    suggestionToEditSection: "הצעת שינוי לסעיף",
    newSectionIn: "סעיף חדש ב-{topic}",
    editSectionIn: "עריכת סעיף ב-{topic}",
    changeDescription: "תיאור השינוי",
    sectionNotFound: "סעיף לא נמצא",
    current: "עדכני",
    lastUpdate: "עדכון אחרון",
    previousVersions: "גרסאות קודמות",
    noDescription: "אין תיאור",
    suggestionAccepted: "הצעה התקבלה",
    sectionCreated: "סעיף נוצר",
    directEdit: "עריכה ישירה",
    viewFullDiscussion: "צפה בדיון המלא",
    changesInThisVersion: "שינויים בגרסה זו:",
    explanationForSuggestion: "הסבר להצעה:",
    pro: "בעד",
    con: "נגד",
    publishedBy: "פורסמה על ידי",
    acceptedOn: "התקבלה ב",
    sectionChangesAutomaticallySaved: "שינויים בסעיף זה יישמרו כאן אוטומטית",
    deleteSection: "מחק סעיף",
    confirmDeleteSection: "האם אתה בטוח שברצונך למחוק סעיף זה?",
    saveToHistory: "שמור בהיסטוריית הגרסאות לפני המחיקה",
    sectionDeleted: "הסעיף נמחק בהצלחה",
    deleting: "מוחק...",
    editSuggestions: "הצעות עריכה",
    noContributors: "אין משתתפים עדיין",
    translate: "תרגם",
    showOriginal: "הצג מקור",
    showTranslation: "הצג תרגום",
    showDiff: "הצג שינויים",
    activityOf: "פעילות של {name}",
    suggestionsPublishedByMe: "הצעות עריכה שפרסמתי",
    suggestionsPublishedBy: "הצעות עריכה שפורסמו על ידי {name}",
    commentsPublishedByMe: "תגובות שפרסמתי",
    commentsPublishedBy: "תגובות שפורסמו על ידי {name}",
    activityHistoryOf: "היסטוריית פעילות של {name}",
    noActivityHistory: "אין עדיין היסטוריית פעילות",
    commentOn: "תגובה על",
    viewFullComment: "צפה בתגובה המלאה",
    suggestion: "הצעה",
    section: "סעיף",
    },
  ar: {
    // التنقل
    home: "الرئيسية",
    myDocuments: "وثائقي",
    newDocument: "وثيقة جديدة",
    suggestions: "المقترحات",
    yourStats: "إحصائياتك",
    logout: "تسجيل الخروج",
    signIn: "تسجيل الدخول",
    profile: "الملف الشخصي",
    
    // الوثيقة
    addSection: "إضافة قسم",
    editSection: "تعديل القسم",
    pendingEditSuggestion: "اقتراح تعديل معلق",
    viewDetails: "عرض التفاصيل",
    proposedChanges: "التغييرات المقترحة",
    lastEdited: "آخر تعديل",
    comments: "التعليقات",
    admin: "الإدارة",
    versions: "الإصدارات",
    
    // المقترحات
    newSuggestion: "اقتراح جديد",
    createNewTopic: "إنشاء موضوع جديد",
    enterNewTopicName: "أدخل اسم الموضوع الجديد...",
    topic: "الموضوع",
    content: "المحتوى",
    explanation: "الشرح (اختياري)",
    createSuggestion: "إنشاء اقتراح",
    cancel: "إلغاء",
    
    // التصويت
    votePro: "صوت مع",
    voteCon: "صوت ضد",
    proVotes: "أصوات مع",
    conVotes: "أصوات ضد",
    consensus: "الإجماع",
    votesNeeded: "أصوات مطلوبة",
    passedConsensus: "تم تجاوز عتبة الإجماع!",
    cannotPass: "لا يمكن التمرير",
    
    // الحالة
    pending: "معلق",
    accepted: "مقبول",
    rejected: "مرفوض",
    
    // الإحصائيات
    contributors: "المساهمون",
    avgConsensus: "متوسط الإجماع",
    threshold: "العتبة",
    activeDocuments: "الوثائق النشطة",
    collaborators: "المشاركون",
    
    // الصفحة الرئيسية
    democraticCollaboration: "منصة التعاون الديمقراطي",
    buildConsensus: "بناء الإجماع، صياغة معًا",
    platformDescription: "منصة تعاونية لصياغة وثائق السياسة والدساتير والقرارات من خلال التصويت الشفاف وخوارزميات الإجماع الديناميكية.",
    getStarted: "ابدأ",
    learnMore: "تعلم المزيد",
    recentDocuments: "الوثائق الأخيرة",
    browseContribute: "تصفح وساهم في المسودات التعاونية الجارية",
    
    // متنوع
    by: "بواسطة",
    noSectionsYet: "لا توجد أقسام حتى الآن.",
    noTopicsYet: "لا توجد مواضيع محددة بعد.",
    loading: "جاري التحميل...",
    insertSectionHere: "أدخل قسم هنا",
    votingEnded: "انتهى التصويت",
    remaining: "متبقية",
    language: "اللغة",
    
    // Additional translations
    suggestNewSection: "اقتراح قسم جديد",
    suggestEditSection: "اقتراح تعديل على القسم",
    enterContent: "أدخل المحتوى...",
    explainChange: "اشرح لماذا هذا التغيير مطلوب...",
    creating: "جارٍ الإنشاء...",
    noSuggestionsYet: "لا توجد مقترحات بعد",
    beFirstToSuggest: "كن أول من يقترح تغييرًا على هذا المستند",
    newSection: "قسم جديد",
    left: "متبقية",
    created: "تم الإنشاء",
    commentsCount: "التعليقات",
    replyingTo: "الرد على",
    writeReply: "اكتب ردًا...",
    addComment: "أضف تعليقًا...",
    postComment: "نشر التعليق",
    loadingComments: "جارٍ تحميل التعليقات...",
    noCommentsYet: "لا توجد تعليقات حتى الآن.",
    beFirstToComment: "كن أول من يعلق!",
    reply: "رد",
    delete: "حذف",
    passedConsensusThreshold: "تجاوز عتبة الإجماع!",
    fullAgreementNeeded: "مطلوب اتفاق كامل",
    votesNeededToPass: "مطلوب {count} أصوات للتمرير",
    noDocumentsYet: "لا توجد مستندات بعد",
    beFirstToCreate: "كن أول من ينشئ مستندًا تعاونيًا",
    documentNotFound: "المستند غير موجود",
    goHome: "العودة إلى الصفحة الرئيسية",
    document: "المستند",
    versionHistory: "سجل الإصدارات",
    compareVersions: "مقارنة الإصدارات",
    cancelComparison: "إلغاء المقارنة",
    noPreviousVersions: "لا توجد إصدارات سابقة",
    documentChangesSavedAutomatically: "يتم حفظ تغييرات المستند تلقائيًا كإصدارات.",
    changeWithoutDescription: "تغيير بدون وصف",
    confirmRestoreVersion: "هل أنت متأكد أنك تريد استعادة هذا الإصدار؟ سيتم حفظ الإصدار الحالي في السجل.",
    restoreVersion: "استعادة الإصدار",
    adminAccessRequired: "مطلوب وصول المسؤول",
    version: "إصدار",
    restoredFromVersion: "تم الاستعادة من الإصدار {version}",
    viewInDocument: "عرض في المستند",
    activitySummary: "ملخص النشاط",
    contributionDescription: "مساهمتك وتاريخ النقاط",
    pointsHistory: "تاريخ النقاط",
    noPointsHistory: "لا يوجد تاريخ نقاط حتى الآن",
    gamificationPoints: "نقاط التلعيب",
    suggestionsCreated: "المقترحات المنشأة",
    accountType: "نوع الحساب",
    translateAll: "ترجمة الكل",
    translating: "جاري الترجمة...",
    translateSection: "ترجمة القسم",
    translatedFrom: "مترجم من",
    points: "نقاط",
    navigation: "التنقل",
    costToCreate: "تكلفة إنشاء اقتراح:",
    yourPoints: "نقاطك:",
    originalContent: "المحتوى الأصلي:",
    cleanView: "عرض نظيف",
    viewCurrentVersion: "لعرض النسخة الحالية من الوثيقة",
    section: "القسم",
    history: "التاريخ",
    personalInformation: "المعلومات الشخصية",
    displayName: "اسم العرض",
    email: "البريد الإلكتروني",
    role: "الدور",
    editProfile: "تعديل الملف الشخصي",
    saveChanges: "حفظ التغييرات",
    action: "الإجراء",
    amount: "الكمية",
    description: "الوصف",
    date: "التاريخ",
    saving: "جارٍ الحفظ...",
    suggestionNotFound: "الاقتراح غير موجود",
    proArguments: "حجج مع",
    conArguments: "حجج ضد",
    noProArgumentsYet: "لا توجد حجج مع حتى الآن",
    noConArgumentsYet: "لا توجد حجج ضد حتى الآن",
    addProArgument: "إضافة حجة مع",
    addConArgument: "إضافة حجة ضد",
    writeProArgument: "اكتب حجتك مع...",
    writeConArgument: "اكتب حجتك ضد...",
    submit: "إرسال",
    proposedContent: "المحتوى المقترح",
    currentVersion: "النسخة الحالية",
    confirmDeleteSuggestion: "هل أنت متأكد أنك تريد حذف هذا الاقتراح؟",
    deleteSuggestion: "حذف الاقتراح",
    commentsOnSuggestion: "التعليقات على الاقتراح",
    onlyCreatorCanDelete: "يمكن للمنشئ فقط حذف هذا الاقتراح",
    mustBeLoggedInToVote: "يجب تسجيل الدخول للتصويت",
    argumentContentRequired: "محتوى الحجة مطلوب",
    mustBeLoggedIn: "يجب تسجيل الدخول",
    acceptSuggestion: "قبول الاقتراح",
    rejectSuggestion: "رفض الاقتراح",
    sectionHistory: "تاريخ القسم",
    createNewDocument: "إنشاء مستند جديد",
    fillDetailsBelow: "املأ التفاصيل أدناه لإنشاء مستند تعاوني جديد",
    signInToViewPrivate: "سجل الدخول لعرض المستندات الخاصة",
    signInToParticipate: "سجل الدخول للمشاركة وإنشاء مقترحات",
    previousSuggestion: "السابق",
    nextSuggestion: "التالي",
    suggestionToEditSection: "اقتراح لتعديل القسم",
    newSectionIn: "قسم جديد في {topic}",
    editSectionIn: "تعديل قسم في {topic}",
    changeDescription: "وصف التغيير",
    sectionNotFound: "القسم غير موجود",
    current: "حالي",
    lastUpdate: "آخر تحديث",
    previousVersions: "النسخ السابقة",
    noDescription: "لا يوجد وصف",
    suggestionAccepted: "تم قبول الاقتراح",
    sectionCreated: "تم إنشاء القسم",
    directEdit: "تحرير مباشر",
    viewFullDiscussion: "عرض المناقشة الكاملة",
    changesInThisVersion: "التغييرات في هذه النسخة:",
    explanationForSuggestion: "شرح الاقتراح:",
    pro: "مع",
    con: "ضد",
    publishedBy: "نشره",
    acceptedOn: "تم القبول في",
    sectionChangesAutomaticallySaved: "سيتم حفظ التغييرات على هذا القسم هنا تلقائيًا",
    deleteSection: "حذف القسم",
    confirmDeleteSection: "هل أنت متأكد أنك تريد حذف هذا القسم؟",
    saveToHistory: "حفظ في سجل الإصدارات قبل الحذف",
    sectionDeleted: "تم حذف القسم بنجاح",
    deleting: "جارٍ الحذف...",
    editSuggestions: "مقترحات تعديل",
    noContributors: "لا يوجد مساهمون بعد",
    translate: "ترجمة",
    showOriginal: "إظهار الأصلي",
    showTranslation: "إظهار الترجمة",
    showDiff: "إظهار التغييرات",
    activityOf: "نشاط {name}",
    suggestionsPublishedByMe: "اقتراحات التحرير التي نشرتها",
    suggestionsPublishedBy: "اقتراحات التحرير التي نشرها {name}",
    commentsPublishedByMe: "التعليقات التي نشرتها",
    commentsPublishedBy: "التعليقات التي نشرها {name}",
    activityHistoryOf: "تاريخ نشاط {name}",
    noActivityHistory: "لا يوجد تاريخ نشاط حتى الآن",
    commentOn: "تعليق على",
    viewFullComment: "عرض التعليق الكامل",
    suggestion: "اقتراح",
    section: "قسم",
    }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('consenz_language') || 'he';
  });

  useEffect(() => {
    localStorage.setItem('consenz_language', language);
    document.documentElement.dir = language === 'en' ? 'ltr' : 'rtl';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key, options = {}) => {
    let translation = translations[language][key] || key;
    for (const optionKey in options) {
      translation = translation.replace(new RegExp(`\\{\\s*${optionKey}\\s*\\}`, 'g'), options[optionKey]);
    }
    return translation;
  };

  const isRTL = language === 'he' || language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <Toaster position="top-center" richColors closeButton dir={isRTL ? 'rtl' : 'ltr'} />
      {children}
    </LanguageContext.Provider>
  );
};