/**
 * TutorialStep interface:
 * {
 *   id: string,
 *   type: 'explain' | 'practice' | 'closing',
 *   targetSelector: string,
 *   tooltipPosition: 'top' | 'bottom' | 'left' | 'right' | 'auto',
 *   heading: string,           // i18n key
 *   body: string,              // i18n key (empty string = no body)
 *   successMessage?: string,   // i18n key
 *   completionEvent?: string,
 *   table?: Array<{label: string, value: string}>
 * }
 */

export const tutorialStrings = {
  he: {
    'home.groups.heading': 'הכל מתחיל מקבוצה',
    'home.groups.body': 'כל קבוצה מנהלת מסמכים משותפים. לחצו על קבוצה כדי לראות את המסמכים שלה — ומשם תוכלו להיכנס לאחד מהם.',
    'group.explain.heading': 'ברוכים הבאים לקבוצה',
    'group.explain.body': 'קבוצה היא מרחב שיתוף פעולה — כאן מתנהלים דיונים, מוצעות שינויים ומתקבלות החלטות יחד. כל קבוצה מכילה מסמכים משותפים שהחברים בה כותבים ומעצבים ביחד.',
    'group.docs.heading': 'בחרו מסמך כדי להמשיך',
    'group.docs.body': 'אלה המסמכים המשותפים של הקבוצה. לחצו על אחד מהם כדי להיכנס ולהתחיל להשתתף.',
    'doc.title.heading': 'כותרת המסמך ותיאורו',
    'doc.title.body': 'כאן מופיעים שם המסמך והרקע שלו — מה הוא עוסק בו ומה מטרתו. קראו אותו לפני שצוללים לסעיפים.',
    'doc.counters.heading': 'נתוני הקהילה במבט מהיר',
    'doc.counters.body': 'הספרות האלה מראות כמה משתתפים פועלים במסמך, כמה תגובות נרשמו, מה רמת הקונצנזוס — וכמה גרסאות כבר התקבלו.',
    'doc.sections.heading': 'סעיפי המסמך',
    'doc.sections.body': 'המסמך מחולק לנושאים וסעיפים. כל סעיף מכיל תוכן שנוצר בשיתוף פעולה, ואפשר להציע לו שינויים.',
    'browse.explain.heading': 'לכל סעיף יש כמה גרסאות',
    'browse.explain.body': 'חברי הקהילה מציעים שינויים לכל סעיף. החצים מאפשרים לעבור ביניהם ולראות מה כל אחד מציע.',
    'browse.practice.heading': 'השתמשו בחצים כדי לעבור בין ההצעות לאחד הסעיפים',
    'browse.practice.success': 'טוב. ככה אפשר תמיד לראות מה הקהילה מציעה לכל חלק במסמך',
    'vote.explain.heading': 'ההצבעה שלכם מעצבת את המסמך',
    'vote.explain.body': 'כל קול קובע. הצבעה בעד מקרבת הצעה לאישור. הצבעה נגד מרחיקה אותה. ההצעה שתצבור מספיק תמיכה תיכנס למסמך.',
    'vote.practice.heading': 'הצביעו על הצעה שמצאתם מעניינת',
    'vote.practice.success': 'ההצבעה נרשמה ותשפיע על תוצאת ההצעה',
    'comment.explain.heading': 'יש מה להוסיף?',
    'comment.explain.body': 'תגובות עוזרות למציע להבין מה עובד ומה לא. זה המקום לשאול, להסביר, או לשכנע.',
    'comment.practice.heading': 'כתבו תגובה קצרה על אחת ההצעות',
    'comment.practice.success': 'התגובה פורסמה',
    'newclause.explain.heading': 'חסר משהו במסמך?',
    'newclause.explain.body': 'אם לדעתכם המסמך צריך נושא שעדיין לא מוזכר — אפשר להציע סעיף חדש לגמרי. אם הקהילה תסכים, הוא ייכנס למסמך.',
    'newclause.practice.heading': 'לחצו על "הוסף סעיף" והציעו תוכן שלדעתכם חסר במסמך',
    'newclause.practice.success': 'ההצעה פורסמה. הקהילה יכולה עכשיו להצביע עליה',
    'editclause.explain.heading': 'לא מסכימים עם ניסוח קיים?',
    'editclause.explain.body': 'אפשר להציע לנסח מחדש כל סעיף — או להציע למחוק אותו לגמרי. גם שינויים כאלה עוברים הצבעה, וגם הם יכולים לשנות את המסמך.',
    'editclause.practice.heading': 'בחרו סעיף קיים והציעו לו ניסוח אחר',
    'editclause.practice.success': 'הצעת השינוי פורסמה',
    'consensus.explain.heading': 'מתי הצעה מתקבלת?',
    'consensus.explain.body': 'לא מספיק רוב — צריך קונסנזוס. הצעה מתקבלת כשפער הקולות בעדה עובר את הרף. הרף מחושב מממוצע ההסכמה ההיסטורי של הקהילה: ככל שהחלטות קודמות התקבלו בהסכמה רחבה יותר — כך הרף לאישורים הבאים גבוה יותר. המסמך מחמיר עם עצמו ככל שהוא בשל יותר.',
    'versions.explain.heading': 'המסמך חי ומשתנה',
    'versions.explain.body': 'כל הצעה שהתקבלה יצרה גרסה חדשה. בעמוד הגרסאות אפשר לראות את ההיסטוריה המלאה — מה השתנה, מתי, ועל ידי מי.',
    'versions.counter.heading': 'לחצו על קאונטר הגרסאות',
    'versions.counter.body': 'המספר הזה מראה כמה גרסאות של המסמך כבר אושרו על ידי הקהילה. לחצו עליו כדי לראות את כל ההיסטוריה.',
    'versions.counter.success': 'כאן אתם רואים את כל השינויים שהקהילה אישרה',
    'versions.navigate.heading': 'לחצו על סוג השינוי שברצונכם לראות',
    'versions.navigate.success': 'כאן מתועד כל שינוי שהקהילה אישרה',
    'cleanview.navigation.heading': 'דפדפו בין הגרסאות הקודמות',
    'cleanview.navigation.body': 'השתמשו בכפתור ״גרסה ישנה יותר״ בתחתית העמוד כדי לנוע בין גרסאות ההיסטוריה של המסמך.',
    'cleanview.navigate.practice.heading': 'לחצו על כפתור ״גרסה ישנה יותר״',
    'cleanview.navigate.practice.body': 'זוהי הדרך לעבור בגרסאות הקודמות ולראות את התפתחות המסמך.',
    'cleanview.navigate.practice.success': 'עברתם לגרסה קודמת של המסמך',
    'cleanview.version.heading': 'הגעתם לגרסה קודמת',
    'cleanview.version.body': 'כל גרסה שתראו כאן מייצגת חלק מההיסטוריה של המסמך — נוצרה בהסכמת הקהילה על בסיס דיון והצבעות של המשתתפים.',
    'cleanview.changetype.heading': 'סוגי השינויים',
    'cleanview.changetype.body': 'כל שינוי מסומן בצבע — ירוק לסעיף חדש, אדום למחיקה, כתום לעריכה. הצבעים עוזרים להבין מה השתנה בגרסה זו.',
    'cleanview.discuss.heading': 'דיון על הסעיף',
    'cleanview.discuss.body': 'לחצו על כל סעיף או שינוי כדי לראות את כל הדיונים, הטיעונים, וההצבעות שהובילו להחלטה זו.',
    'points.explain.heading': 'תרומה אמיתית מזכה בנקודות',
    'points.explain.body': 'הגשת הצעה עולה נקודות — זה מסנן רעש ומבטיח שכל הצעה רצינית. אבל אם ההצעה מקבלת תמיכה — מחזירים הרבה יותר ממה שהושקע.',
    'points.explain.cost.edit': 'הצעת עריכה לסעיף',
    'points.explain.cost.new': 'הצעת סעיף חדש',
    'points.explain.reward.upvote': 'כל הצבעת בעד על ההצעה',
    'points.explain.reward.aligned': 'הצבעה בכיוון הקהילה',
    'points.explain.reward.accepted': 'הצעה שהתקבלה',
    'closing.heading': 'מוכנים לתרום',
    'closing.body': 'עכשיו אתם יודעים איך Consenz עובדת. כל הצעה שתגישו, כל הצבעה שתתנו — מעצבת את המסמך הזה יחד עם שאר הקהילה.',
    'closing.cta': 'בואו נתחיל',
    'nav.restart': 'סיור בפלטפורמה',
    'signup.prompt.heading': 'כדי להמשיך צריך להירשם',
    'signup.prompt.body': 'ההרשמה חינמית ולוקחת שניות. אחרי ההרשמה תחזרו בדיוק לכאן.',
    'signup.prompt.cta': 'הרשמה',
  },
  ar: {
    'home.groups.heading': 'كل شيء يبدأ من مجموعة',
    'home.groups.body': 'كل مجموعة تدير وثائق مشتركة. اضغطوا على مجموعة لرؤية وثائقها — ومن هناك يمكنكم الدخول إلى إحداها.',
    'group.explain.heading': 'مرحباً بكم في المجموعة',
    'group.explain.body': 'المجموعة هي فضاء للتعاون — هنا تجري النقاشات، تُقترح التعديلات وتُتخذ القرارات معاً. تحتوي كل مجموعة على وثائق مشتركة يكتبها الأعضاء ويشكّلونها سوياً.',
    'group.docs.heading': 'اختاروا وثيقة للمتابعة',
    'group.docs.body': 'هذه هي الوثائق المشتركة للمجموعة. اضغطوا على إحداها للدخول والمشاركة.',
    'doc.title.heading': 'عنوان الوثيقة ووصفها',
    'doc.title.body': 'هنا يظهر اسم الوثيقة وخلفيتها — ما الذي تتناوله وما هدفها. اقرأوهما قبل التعمق في البنود.',
    'doc.counters.heading': 'بيانات المجتمع في لمحة سريعة',
    'doc.counters.body': 'تُظهر هذه الأرقام عدد المشاركين النشطين في الوثيقة، وعدد التعليقات المسجلة، ومستوى التوافق — وعدد الإصدارات المقبولة.',
    'doc.sections.heading': 'بنود الوثيقة',
    'doc.sections.body': 'الوثيقة مقسمة إلى مواضيع وبنود. كل بند يحتوي على محتوى أُنشئ بشكل تعاوني، ويمكن اقتراح تعديلات عليه.',
    'browse.explain.heading': 'لكل بند عدة نسخ',
    'browse.explain.body': 'يقترح أعضاء المجتمع تعديلات على كل بند. تتيح لكم الأسهم التنقل بينها ورؤية ما يقترحه كل شخص.',
    'browse.practice.heading': 'استخدموا الأسهم للتنقل بين المقترحات',
    'browse.practice.success': 'ممتاز. هكذا يمكن دائماً معرفة ما يقترحه المجتمع لكل جزء من الوثيقة',
    'vote.explain.heading': 'تصويتكم يشكّل الوثيقة',
    'vote.explain.body': 'كل صوت مهم. التصويت لصالح مقترح يقرّبه من القبول. التصويت ضده يبعده. المقترح الذي يحصل على دعم كافٍ سيدخل الوثيقة.',
    'vote.practice.heading': 'صوّتوا على مقترح وجدتموه مثيراً للاهتمام',
    'vote.practice.success': 'تم تسجيل تصويتكم وسيؤثر على نتيجة المقترح',
    'comment.explain.heading': 'هل لديكم ما تضيفونه؟',
    'comment.explain.body': 'تساعد التعليقات صاحب المقترح على فهم ما يناسب وما لا يناسب. هذا هو المكان للسؤال والشرح والإقناع.',
    'comment.practice.heading': 'اكتبوا تعليقاً قصيراً على أحد المقترحات',
    'comment.practice.success': 'تم نشر تعليقكم',
    'newclause.explain.heading': 'هل يغيب شيء عن الوثيقة؟',
    'newclause.explain.body': 'إذا رأيتم أن الوثيقة تحتاج إلى موضوع لم يُذكر بعد — يمكنكم اقتراح بند جديد كلياً. إذا وافق المجتمع، سيُضاف إلى الوثيقة.',
    'newclause.practice.heading': 'اضغطوا على "إضافة بند" واقترحوا محتوى ترون أنه مفقود',
    'newclause.practice.success': 'تم نشر المقترح. يمكن للمجتمع الآن التصويت عليه',
    'editclause.explain.heading': 'لا توافقون على صياغة موجودة؟',
    'editclause.explain.body': 'يمكنكم اقتراح إعادة صياغة أي بند — أو اقتراح حذفه كلياً. هذه التغييرات أيضاً تخضع للتصويت ويمكنها تعديل الوثيقة.',
    'editclause.practice.heading': 'اختاروا بنداً موجوداً واقترحوا له صياغة مختلفة',
    'editclause.practice.success': 'تم نشر مقترح التعديل',
    'consensus.explain.heading': 'متى يُقبل المقترح؟',
    'consensus.explain.body': 'الأغلبية وحدها لا تكفي — نحتاج إلى توافق. يُقبل المقترح عندما يتجاوز فارق الأصوات لصالحه العتبة المطلوبة. تُحسب هذه العتبة من متوسط التوافق التاريخي للمجتمع: كلما اتُّخذت القرارات السابقة بتوافق أوسع، ارتفعت العتبة للموافقات القادمة.',
    'versions.explain.heading': 'الوثيقة حية ومتطورة',
    'versions.explain.body': 'كل مقترح قُبل أنشأ نسخة جديدة. في صفحة النسخ يمكنكم رؤية التاريخ الكامل — ما الذي تغيّر، ومتى، ومن اقترحه.',
    'versions.counter.heading': 'انقروا على عداد النسخ',
    'versions.counter.body': 'هذا الرقم يُظهر كم نسخة من الوثيقة وافق عليها المجتمع. انقروا عليه لرؤية التاريخ الكامل.',
    'versions.counter.success': 'هنا ترون جميع التغييرات التي وافق عليها المجتمع',
    'versions.navigate.heading': 'انقروا على نوع التغيير الذي تريدون رؤيته',
    'versions.navigate.success': 'هنا يُوثَّق كل تغيير وافق عليه المجتمع',
    'cleanview.navigation.heading': 'تنقلوا بين الإصدارات السابقة',
    'cleanview.navigation.body': 'استخدموا زر ״إصدار أقدم״ في أسفل الصفحة للانتقال بين إصدارات تاريخ الوثيقة.',
    'cleanview.navigate.practice.heading': 'اضغطوا على زر ״إصدار أقدم״',
    'cleanview.navigate.practice.body': 'هذه هي الطريقة للانتقال بين الإصدارات السابقة ورؤية تطور الوثيقة.',
    'cleanview.navigate.practice.success': 'انتقلتم إلى إصدار سابق من الوثيقة',
    'cleanview.version.heading': 'وصلتم إلى إصدار سابق',
    'cleanview.version.body': 'كل إصدار ترونه هنا يمثل جزءاً من تاريخ الوثيقة — تم إنشاؤه بإجماع المجتمع على أساس النقاش والتصويت من المشاركين.',
    'cleanview.changetype.heading': 'أنواع التغييرات',
    'cleanview.changetype.body': 'كل تغيير مشفر بألوان — أخضر لقسم جديد، أحمر للحذف، برتقالي للتعديل. تساعد الألوان على فهم ما تغيّر في هذا الإصدار.',
    'cleanview.discuss.heading': 'نقاش حول القسم',
    'cleanview.discuss.body': 'انقروا على أي قسم أو تغيير لرؤية جميع النقاشات والحجج والتصويتات التي أدت إلى هذا القرار.',
    'points.explain.heading': 'المساهمة الحقيقية تُكسب نقاطاً',
    'points.explain.body': 'تقديم مقترح يكلّف نقاطاً — هذا يُصفّي الضوضاء ويضمن جدية كل مقترح. لكن إذا حصل المقترح على دعم، ستستردون أكثر مما أنفقتم.',
    'points.explain.cost.edit': 'اقتراح تعديل بند',
    'points.explain.cost.new': 'اقتراح بند جديد',
    'points.explain.reward.upvote': 'كل تصويت لصالح مقترحكم',
    'points.explain.reward.aligned': 'التصويت في اتجاه المجتمع',
    'points.explain.reward.accepted': 'مقترح تم قبوله',
    'closing.heading': 'أنتم مستعدون للمساهمة',
    'closing.body': 'الآن تعرفون كيف تعمل Consenz. كل مقترح تقدمونه، وكل تصويت تمنحونه — يُشكّل هذه الوثيقة مع بقية المجتمع.',
    'closing.cta': 'لنبدأ',
    'nav.restart': 'جولة في المنصة',
    'signup.prompt.heading': 'للمتابعة يجب التسجيل',
    'signup.prompt.body': 'التسجيل مجاني ويستغرق ثوانٍ. بعد التسجيل ستعودون إلى هنا مباشرة.',
    'signup.prompt.cta': 'تسجيل',
  },
  en: {
    'home.groups.heading': 'Everything starts with a group',
    'home.groups.body': 'Each group manages shared documents. Click on a group to see its documents — and from there you can enter one.',
    'group.explain.heading': 'Welcome to the group',
    'group.explain.body': 'A group is a collaboration space — this is where discussions happen, changes are proposed, and decisions are made together. Each group contains shared documents that members write and shape collectively.',
    'group.docs.heading': 'Pick a document to continue',
    'group.docs.body': "These are the group's shared documents. Click one to enter and start participating.",
    'doc.title.heading': 'Document title and description',
    'doc.title.body': 'This shows the document name and its background — what it covers and what its purpose is. Read it before diving into the clauses.',
    'doc.counters.heading': 'Community stats at a glance',
    'doc.counters.body': 'These numbers show how many participants are active in the document, how many comments have been posted, the consensus level — and how many versions have been accepted.',
    'doc.sections.heading': 'Document sections',
    'doc.sections.body': 'The document is divided into topics and sections. Each section contains collaboratively created content, and you can propose changes to it.',
    'browse.explain.heading': 'Each clause has multiple versions',
    'browse.explain.body': 'Community members propose changes to each clause. Use the arrows to browse between proposals and see what each one suggests.',
    'browse.practice.heading': 'Use the arrows to browse proposals on any clause',
    'browse.practice.success': 'Nice — you can always flip through proposals this way',
    'vote.explain.heading': 'Your vote shapes the document',
    'vote.explain.body': 'Every vote counts. Voting for a proposal brings it closer to approval. Voting against pushes it away. The proposal with enough support becomes part of the document.',
    'vote.practice.heading': 'Vote on a proposal you find interesting',
    'vote.practice.success': 'Your vote has been counted and will affect the outcome',
    'comment.explain.heading': 'Have something to add?',
    'comment.explain.body': "Comments help the author understand what works and what doesn't. This is the place to ask, explain, or persuade.",
    'comment.practice.heading': 'Write a short comment on any proposal',
    'comment.practice.success': 'Your comment is live',
    'newclause.explain.heading': 'Something missing from the document?',
    'newclause.explain.body': 'If you think the document needs a topic that isn\'t covered yet — you can propose an entirely new clause. If the community agrees, it will be added to the document.',
    'newclause.practice.heading': 'Click "Add clause" and propose content you think is missing',
    'newclause.practice.success': 'Your proposal is live. The community can now vote on it',
    'editclause.explain.heading': 'Disagree with existing wording?',
    'editclause.explain.body': 'You can propose rewording any clause — or propose deleting it entirely. These changes go through a vote too, and they can change the document.',
    'editclause.practice.heading': 'Pick an existing clause and propose different wording',
    'editclause.practice.success': 'Your change proposal is live',
    'consensus.explain.heading': 'When does a proposal get accepted?',
    'consensus.explain.body': 'A majority isn\'t enough — you need consensus. A proposal passes when the gap between for and against votes crosses the threshold. The threshold is calculated from the community\'s historical agreement average: the broader the consensus on past decisions, the higher the bar for future approvals. The document holds itself to a higher standard as it matures.',
    'versions.explain.heading': 'The document is alive and evolving',
    'versions.explain.body': 'Every accepted proposal created a new version. In the versions page you can see the full history — what changed, when, and by whom.',
    'versions.counter.heading': 'Click the versions counter to explore',
    'versions.counter.body': 'This number shows how many versions of the document have been approved by the community. Click it to see the full history.',
    'versions.counter.success': 'Here you see all the changes the community has approved',
    'versions.navigate.heading': 'Click on a change type to see',
    'versions.navigate.success': 'Every change the community approved is documented here',
    'cleanview.navigation.heading': 'Browse older versions',
    'cleanview.navigation.body': 'Use the "Older version" button at the bottom to move between versions of the document history.',
    'cleanview.navigate.practice.heading': 'Click the "Older version" button',
    'cleanview.navigate.practice.body': 'This is how you browse through previous versions and see the document\'s evolution.',
    'cleanview.navigate.practice.success': 'You\'ve navigated to an older version',
    'cleanview.version.heading': 'You\'re viewing an older version',
    'cleanview.version.body': 'Every version you see here represents part of the document\'s history — created by community consensus based on discussion and voting from participants.',
    'cleanview.changetype.heading': 'Types of changes',
    'cleanview.changetype.body': 'Each change is color-coded — green for new section, red for deletion, orange for edit. Colors help you understand what changed in this version.',
    'cleanview.discuss.heading': 'Discussion on the section',
    'cleanview.discuss.body': 'Click on any section or change to see all the discussions, arguments, and votes that led to this decision.',
    'points.explain.heading': 'Real contributions earn points',
    'points.explain.body': 'Submitting a proposal costs points — this filters noise and ensures every proposal is serious. But if your proposal earns support, you get back far more than you invested.',
    'points.explain.cost.edit': 'Propose a clause edit',
    'points.explain.cost.new': 'Propose a new clause',
    'points.explain.reward.upvote': 'Each upvote on your proposal',
    'points.explain.reward.aligned': 'Voting in line with the community',
    'points.explain.reward.accepted': 'Proposal accepted',
    'closing.heading': 'You\'re ready to contribute',
    'closing.body': 'Now you know how Consenz works. Every proposal you submit, every vote you cast — shapes this document together with the rest of the community.',
    'closing.cta': 'Let\'s go',
    'nav.restart': 'Platform tour',
    'signup.prompt.heading': "You'll need an account to continue",
    'signup.prompt.body': "Signing up is free and takes seconds. After registering you'll be brought right back here.",
    'signup.prompt.cta': 'Sign up',
  },
};

/**
 * Resolve an i18n key to the translated string.
 * Falls back to Hebrew, then the key itself.
 */
export function tTutorial(key, language = 'he') {
  if (!key) return '';
  const lang = tutorialStrings[language] || tutorialStrings.he;
  return lang[key] || tutorialStrings.he[key] || key;
}

/**
 * Mid-tutorial steps shown on the group page.
 * Step 1: Explain what a group is.
 * Step 2: Guide user to click a document.
 */
export const GROUP_EXPLAIN_STEP = {
  id: 'group-explain',
  type: 'explain',
  targetSelector: '.group-header',
  tooltipPosition: 'bottom',
  heading: 'group.explain.heading',
  body: 'group.explain.body',
};

export const GROUP_INTRO_STEP = {
  id: 'group-intro',
  type: 'practice',
  targetSelector: '.group-documents-list',
  tooltipPosition: 'bottom',
  heading: 'group.docs.heading',
  body: 'group.docs.body',
  successMessage: 'מעולה, בואו נתחיל',
  completionEvent: 'document:entered',
};

/**
 * Pre-tutorial step shown on the home page.
 * No progress dots, no scrim — spotlight only on .groups-list.
 */
export const HOME_INTRO_STEP = {
  id: 'home-intro',
  type: 'practice',
  targetSelector: '.groups-list',
  tooltipPosition: 'bottom',
  heading: 'home.groups.heading',
  body: 'home.groups.body',
  successMessage: 'מעולה, בואו נתחיל',
  completionEvent: 'document:entered',
};

/** @type {Array} */
export const TUTORIAL_STEPS = [
  {
    id: 'doc-title-explain',
    type: 'explain',
    targetSelector: '.document-title-area',
    tooltipPosition: 'bottom',
    heading: 'doc.title.heading',
    body: 'doc.title.body',
  },
  {
    id: 'doc-counters-explain',
    type: 'explain',
    targetSelector: '.document-counters',
    tooltipPosition: 'bottom',
    heading: 'doc.counters.heading',
    body: 'doc.counters.body',
  },
  {
    id: 'doc-sections-explain',
    type: 'explain',
    targetSelector: '.document-sections-area',
    tooltipPosition: 'top',
    heading: 'doc.sections.heading',
    body: 'doc.sections.body',
  },
  {
    id: 'browse-explain',
    type: 'explain',
    targetSelector: '.proposal-navigation-arrows',
    tooltipPosition: 'bottom',
    heading: 'browse.explain.heading',
    body: 'browse.explain.body',
  },
  {
    id: 'vote-explain',
    type: 'explain',
    targetSelector: '.proposal-vote-buttons',
    tooltipPosition: 'top',
    heading: 'vote.explain.heading',
    body: 'vote.explain.body',
  },
  {
    id: 'comment-explain',
    type: 'explain',
    targetSelector: '.proposal-comment-input',
    tooltipPosition: 'top',
    heading: 'comment.explain.heading',
    body: 'comment.explain.body',
  },
  {
    id: 'newclause-explain',
    type: 'explain',
    targetSelector: '.add-clause-button',
    tooltipPosition: 'bottom',
    heading: 'newclause.explain.heading',
    body: 'newclause.explain.body',
  },
  {
    id: 'editclause-explain',
    type: 'explain',
    targetSelector: '.clause-edit-button',
    tooltipPosition: 'top',
    heading: 'editclause.explain.heading',
    body: 'editclause.explain.body',
  },
  {
    id: 'consensus-explain',
    type: 'explain',
    targetSelector: '.consensus-meter',
    tooltipPosition: 'bottom',
    heading: 'consensus.explain.heading',
    body: 'consensus.explain.body',
  },
  {
    id: 'versions-explain',
    type: 'explain',
    targetSelector: '.versions-tab-button',
    tooltipPosition: 'bottom',
    heading: 'versions.explain.heading',
    body: 'versions.explain.body',
  },
  {
    id: 'versions-counter-practice',
    type: 'practice',
    targetSelector: '.versions-counter',
    tooltipPosition: 'bottom',
    heading: 'versions.counter.heading',
    body: 'versions.counter.body',
    successMessage: 'versions.counter.success',
    completionEvent: 'versions:opened',
  },
  {
    id: 'versions-navigate',
    type: 'practice',
    targetSelector: '.versions-tab-button',
    tooltipPosition: 'bottom',
    heading: 'versions.navigate.heading',
    body: '',
    successMessage: 'versions.navigate.success',
    completionEvent: 'versions:opened',
  },
  {
    id: 'cleanview-navigation-intro',
    type: 'explain',
    targetSelector: '.document-clean-view-container',
    tooltipPosition: 'bottom',
    heading: 'cleanview.navigation.heading',
    body: 'cleanview.navigation.body',
  },
  {
    id: 'cleanview-navigation-practice',
    type: 'practice',
    targetSelector: '.older-version-button',
    tooltipPosition: 'top',
    heading: 'cleanview.navigate.practice.heading',
    body: 'cleanview.navigate.practice.body',
    successMessage: 'cleanview.navigate.practice.success',
    completionEvent: 'version:navigated',
  },
  {
    id: 'cleanview-version',
    type: 'explain',
    targetSelector: '.version-metadata',
    tooltipPosition: 'bottom',
    heading: 'cleanview.version.heading',
    body: 'cleanview.version.body',
  },
  {
    id: 'cleanview-changetype',
    type: 'explain',
    targetSelector: '.versions-counter',
    tooltipPosition: 'bottom',
    heading: 'cleanview.changetype.heading',
    body: 'cleanview.changetype.body',
  },
  {
    id: 'cleanview-discuss',
    type: 'explain',
    targetSelector: '.section-content-clickable',
    tooltipPosition: 'top',
    heading: 'cleanview.discuss.heading',
    body: 'cleanview.discuss.body',
  },
  {
    id: 'points-explain',
    type: 'explain',
    targetSelector: '.user-points-badge',
    tooltipPosition: 'bottom',
    heading: 'points.explain.heading',
    body: 'points.explain.body',
    table: [
      { label: 'points.explain.cost.edit',       value: '−200' },
      { label: 'points.explain.cost.new',        value: '−350' },
      { label: 'points.explain.reward.upvote',   value: '+10'  },
      { label: 'points.explain.reward.aligned',  value: '+50'  },
      { label: 'points.explain.reward.accepted', value: '+500' },
    ],
  },
  {
    id: 'closing',
    type: 'closing',
    targetSelector: null,
    tooltipPosition: null,
    heading: 'closing.heading',
    body: 'closing.body',
    cta: 'closing.cta',
  },
];