import js from '@eslint/js';

const vitestGlobals = {
  describe: 'readonly',
  test: 'readonly',
  it: 'readonly',
  expect: 'readonly',
  beforeEach: 'readonly',
  afterEach: 'readonly',
  beforeAll: 'readonly',
  afterAll: 'readonly',
  vi: 'readonly',
};

const browserGlobals = {
  window: 'readonly',
  document: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  navigator: 'readonly',
  location: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  Event: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  Promise: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  Symbol: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  JSON: 'readonly',
  Math: 'readonly',
  Date: 'readonly',
  Array: 'readonly',
  Object: 'readonly',
  String: 'readonly',
  Number: 'readonly',
  Boolean: 'readonly',
  Error: 'readonly',
  TypeError: 'readonly',
  RangeError: 'readonly',
  parseInt: 'readonly',
  parseFloat: 'readonly',
  isNaN: 'readonly',
  isFinite: 'readonly',
  encodeURIComponent: 'readonly',
  decodeURIComponent: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  FileReader: 'readonly',
  FormData: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  WebSocket: 'readonly',
  performance: 'readonly',
  crypto: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
};

export default [
  // 1. Global ignores — test/spec/qa files never linted
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      'src/components/qa/**',
      'components/qa/**',
      'src/components/document/__tests__/**',
      'components/document/__tests__/**',
      '**/__tests__/**',
      '**/__test__/**',
      '**/test/**',
      '**/tests/**',
      '**/*.test.js',
      '**/*.test.jsx',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.js',
      '**/*.spec.jsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/*.md.jsx',
      '**/*.md.tsx',
      '**/*.md.js',
      '**/QAReport*',
      '**/consensusMeter*',
    ],
  },
  // 2. Production source files
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    ignores: [
      '**/QAReport*',
      'src/**/QAReport*',
      'src/**/__tests__/**',
      '**/__tests__/**',
      'src/**/*.test.{js,jsx,ts,tsx}',
      'src/**/*.spec.{js,jsx,ts,tsx}',
      'src/**/consensusMeter*',
      '**/consensusMeter*',
      'src/components/qa/**',
      'components/qa/**',
      '**/*.md.jsx',
      '**/*.md.tsx',
      '**/*.md.js',
    ],
    rules: {
      ...js.configs.recommended.rules,
      'no-unused-vars': 'warn',
      'no-undef': 'error',
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...browserGlobals, ...vitestGlobals },
    },
  },
  // 3. Explicit override for any test files that slip through — disable no-undef entirely
  {
    files: [
      '**/__tests__/**/*.{js,jsx,ts,tsx}',
      '**/*.test.{js,jsx,ts,tsx}',
      '**/*.spec.{js,jsx,ts,tsx}',
      'src/**/__tests__/**/*.{js,jsx,ts,tsx}',
      'src/**/*.test.{js,jsx,ts,tsx}',
      'src/**/*.spec.{js,jsx,ts,tsx}',
    ],
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...browserGlobals, ...vitestGlobals },
    },
  },
  // 4. QA markdown-as-jsx files — parser may fail, skip entirely
  {
    files: ['**/*.md.jsx', '**/*.md.tsx', 'src/components/qa/**'],
    rules: {
      'no-undef': 'off',
      'no-unused-vars': 'off',
    },
  },
];